name: adaptive_margin_svls
margin: 3
alpha: 0.1
beta: 0
ignore_index: -100
schedule: ""
mu: 0
max_alpha: 100.0
step_size: 100
numclasses: 4
kernel_size: 3
kernel_ops: 'mean'


object:
  _target_: calibrate.losses.AdaptMarginSVLS
  margin: ${loss.margin}
  alpha: ${loss.alpha}
  beta: ${loss.beta}
  ignore_index: ${loss.ignore_index}
  mu: ${loss.mu}
  schedule: ${loss.schedule}
  max_alpha: ${loss.max_alpha}
  step_size: ${loss.step_size}
  classes: ${loss.numclasses}
  kernel_size: ${loss.kernel_size}
  kernel_ops: ${loss.kernel_ops}