name: adaptive_margin_svls
alpha: 0.1
ignore_index: -100
schedule: ""
mu: 0
sigma: 1
max_alpha: 100.0
step_size: 100
numclasses: 4
kernel_size: 3
kernel_ops: 'mean'
distance_type: 'l1'
is_softmax: False

object:
  _target_: calibrate.losses.AdaptMarginSVLS
  alpha: ${loss.alpha}
  ignore_index: ${loss.ignore_index}
  mu: ${loss.mu}
  sigma: ${loss.sigma}
  schedule: ${loss.schedule}
  max_alpha: ${loss.max_alpha}
  step_size: ${loss.step_size}
  classes: ${loss.numclasses}
  kernel_size: ${loss.kernel_size}
  kernel_ops: ${loss.kernel_ops}
  distance_type: ${loss.distance_type}
  is_softmax: ${loss.is_softmax}