#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce_dice" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="svls" loss.numclasses="4" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" loss.gamma="1" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" loss.gamma="2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"

#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="5" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="8" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#

# CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
# CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" loss.gamma="1" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" loss.gamma="2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100"


#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="0" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 


#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="11" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="12" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="13" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="14" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="15" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="6" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="7" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain" data.batch_size="16" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="9" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="100" 


## balancing lambda 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" loss.alpha="0.05"  optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" loss.alpha="0.2"  optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" loss.alpha="0.3"  optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" 

## seeds
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin"  optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin"  optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce_dice" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ce_dice" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="focal" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="penalty_ent" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="ls" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2

#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="svls" loss.numclasses="4" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=0
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="svls" loss.numclasses="4" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50" seed=2


#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin_l2" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"

CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=False task="medseg" data="brain19" data.batch_size="64" model="unet" model.num_classes="4" model.num_inp_channels="4" loss="logit_margin_dice" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-brain" log_period="100" train.max_epoch="50"
