#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="ce" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="ce_dice" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="focal" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="penalty_ent" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="ls" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="svls" loss.numclasses="5" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="ls" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="ls" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="0" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="5" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="8" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="focal" loss.gamma="1" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="focal" loss.gamma="2" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="penalty_ent" loss.alpha="0.2" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="penalty_ent" loss.alpha="0.3" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"



# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="11" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="12" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="13" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="14" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="9" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="7" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="6" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin_adaptive" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

##unet++
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unetpp" model.num_inp_channels="1" model.num_classes="5" loss="ce" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unetpp" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unetpp" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="5" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unetpp" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="8" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="unetpp" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

##transunet
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="transunet" loss="ce" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="25"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="transunet" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="transunet" loss="logit_margin" loss.margin="5" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
# CUDA_VISIBLE_DEVICES=5 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="transunet" loss="logit_margin" loss.margin="3" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

##attunet
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="attunet" model.num_inp_channels="1" model.num_classes="5" loss="ce" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="attunet" model.num_inp_channels="1" model.num_classes="5" loss="logit_margin" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

##dynunet
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="nnunet" model.num_inp_channels="1" model.num_classes="5" loss="msce" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"
#CUDA_VISIBLE_DEVICES=4 python tools/train_net.py wandb.enable=True task="medseg" data="abdomen" data.batch_size="16" model="nnunet" model.num_inp_channels="1" model.num_classes="5" loss="mscelogit" optim="adam" scheduler="step" wandb.project="unet-abdomen" train.max_epoch="100" log_period="100"

